docker_image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
env_name: "py38"
conda_env_file: "env-py38.yml"
conda_binary: "mamba"
python_version: "3.8"
pkg_name: ""
pkg_version: ""
extra_packages: "mamba"
channels: "-c conda-forge"
